### PR TITLE
Fixes Tests and adds GitHub action

### PR DESCRIPTION
**Pull request by geekskick**
Removed the local copy of catch2 and gets it as needed, also allows the bool test to pass based on clarification in #7 . The floating point string formatting now works for all but the long double, this test fails, so a separate PR will be submitted against the actual tortellini.hh file for this as requested. 

All tests now run on push on GitHub Actions on 3 architectures with a time out of 3 minutes - this will fail when it runs because of the long double stuff.

### CODE REVIEW

**Comment by Qix-** [comment]
Hey, not really crazy about these changes. If you'd like to re-open a PR that adds a github action, then I'd happily accept that. As-is, I don't want to replace the build system, and I don't want to strip out catch.

**Comment by Qix-** [comment]
Nevermind, there was no build system. My last comment made no sense. Changes look OK, thank you again for all the work you've done :)

**Comment by Qix-** [comment]
Nevermind, my last comment made no sense. Been a minute since I've looked at this repo, apologies.

Can you add back catch2? I don't have a problem with the vendored test suite, and I certainly do not like build scripts pulling files from the internet.

**Comment by geekskick** [comment]
Sure

**Comment by Qix-** [comment]
Thanks again, though I think I might switch to CMake so that we're not relying upon compiler-specific flags and that tests can be run on Windows.

**Comment by geekskick** [comment]
Im confused by the last comment - which compiler specific flags do you mean? And isn't it running on windows already?

**Comment by Qix-** [comment]
The `makefile` uses `g++` and `-std=c++11` for example, along with the other `-x` flags - none of which work on MSVC.

Plus, the inclusion of the tests in the CTest suite means that Tortellini would be tested along with other dependencies in larger projects.

**Pull request merged**
